import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  env: {
    MONAD_RPC_URL: process.env.MONAD_RPC_URL,
    MONAD_CHAIN_ID: process.env.MONAD_CHAIN_ID,
    DEPLOYER_PRIVATE_KEY: process.env.DEPLOYER_PRIVATE_KEY,
    SANDBOX_ADDRESS: process.env.SANDBOX_ADDRESS,
    NEXT_PUBLIC_MONAD_RPC_URL: process.env.NEXT_PUBLIC_MONAD_RPC_URL,
    NEXT_PUBLIC_MONAD_CHAIN_ID: process.env.NEXT_PUBLIC_MONAD_CHAIN_ID,
    NEXT_PUBLIC_RUNNER_AUTO: process.env.NEXT_PUBLIC_RUNNER_AUTO,
    NEXT_PUBLIC_RESERVE_DROP_BPS: process.env.NEXT_PUBLIC_RESERVE_DROP_BPS,
    NEXT_PUBLIC_RESERVE_WINDOW_BLOCKS:
      process.env.NEXT_PUBLIC_RESERVE_WINDOW_BLOCKS,
    NEXT_PUBLIC_PRICE_SHOCK: process.env.NEXT_PUBLIC_PRICE_SHOCK,
    NEXT_PUBLIC_COOLDOWN_BLOCKS: process.env.NEXT_PUBLIC_COOLDOWN_BLOCKS,
    NEXT_PUBLIC_WITHDRAW_LIMIT_BPS: process.env.NEXT_PUBLIC_WITHDRAW_LIMIT_BPS,
    NEXT_PUBLIC_RUNNER_POLL_MS: process.env.NEXT_PUBLIC_RUNNER_POLL_MS,
    NEXT_PUBLIC_RUNNER_LOOKBACK: process.env.NEXT_PUBLIC_RUNNER_LOOKBACK,
  },
}

export default nextConfig
